### ISSUE TITLE
Possible GNPLT bug displaying Tsys vs elevation

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#104]
I use GNPLT on our FS10 test machine to process a logfile written by FS 9.12.12. Perhaps this is not sensible, but I am still surprised by the results. The relevant files are on the FS10 test machine, which @wehimwich has access to in Onsala. To replicate my confusion, please follow these steps in GNPLT:

File-->New-->/usr2/oper/eskil/ONOFF_20210304/ottn.log
Edit-->Delete points with bad GC
Edit-->Gain vs El-->Left-->All-->018u
Shows reasonable gain plot:
<img width="969" alt="gain" src="https://user-images.githubusercontent.com/8872291/113002982-965e6500-9172-11eb-9e85-0d91396ca82e.png">
If I now select
Y-axis-->SEFD I also get reasonable SEFD plot:
<img width="964" alt="sefd" src="https://user-images.githubusercontent.com/8872291/113003669-3d430100-9173-11eb-822a-5ccd60ddf96f.png">

**However**: If I select
Y-axis-->Tsys (still vs elevation for detector 018u) I get a very surprising curve:
<img width="965" alt="tsys" src="https://user-images.githubusercontent.com/8872291/113003093-af671600-9172-11eb-807e-622de3e11721.png">

I would expect Tsys to be around 50K, and rising at lower elevations. Indeed, looking at the logfile VAL output for this detector (e.g. using "oper@njord:~/eskil/ONOFF_20210304$ grep VAL ottn.log | grep 018u") it seems to be true: Tsys round 45K rising to 60K at 10 deg elevation. So what is going on with this plot?

Is GNPLT wrong in the Tsys display, or have I missed something?

**Comment by wehimwich** [comment]
I don't know. It doesn't seem right. Have you plotted Tsys vs elevation before and had sensible behavior?

@BeppeMc had privately reported a different issue related to Tsys plotting about 12 hours ago. I had planned to look into that next week. That seemed like it could be a _gndat_ issue, but it is too early to tell.

**Comment by varenius** [comment]
I have not plotted Tsys vs elevation before, so I cannot say if it is a new or old issue.
