### ISSUE TITLE
gnplt doesn't extract Tsys from the log file correctly

### ISSUE THREAD

**Issue by wehimwich** [nvi-inc/fs#107]
On Mar 30, 2021, at 4:47 AM, @BeppeMC wrote:

> Form my analysis seem a Tsys wrong extraction from log file, because I have in plot tsys values that aren't in log file (see screen-shot, ![gnplt2](https://user-images.githubusercontent.com/51408905/113596108-d8225c00-9607-11eb-814a-8609a023496b.png).
>
> I cannot check in proof because the gnplot2 temporary file is immediately purged after the extraction (would be nice if it stay alive for the whole gnplt session). But I catch one of them after a program abort, and I can see that extracted tsys suddenly  jump to 5 hundred and more without any explanation, while the other parameters are still choerent ( see the extraction below). I noticed that also weather data are not read properly.
> 
> By the while, I attach 3.2MB log file ([chc23Mar21.log.gz](https://github.com/nvi-inc/fs/files/6259097/chc23Mar21.log.gz)), so you can try on your side.
> 
> Thanks, Beppe
>
> Partial extraction: [data.txt](https://github.com/nvi-inc/fs/files/6259121/data.txt).

**Comment by wehimwich** [comment]
On Mar 30, 2021, at 12:11 PM, @BeppeMc wrote:

The _.rxg_ file [chcMc.txt](https://github.com/nvi-inc/fs/files/6259477/chcMc.txt) used for acquisition in example.

**Comment by BeppeMc** [comment]
Yes, problem fixed. Now tsys has the expected behaviour with airmass and elevation.
I used the gndat_test branch on FS-10.0.0(final)
![chcMc](https://user-images.githubusercontent.com/52746223/113696008-031cb680-96c1-11eb-81b5-bb3cc93efd28.png)

Thanks, Beppe.

**Comment by wehimwich** [comment]
This symptom, and the one on #104, is caused by a mis-sized array in _gndat_. There should have been no problem analyzing logs with 20 or less detectors per _onoff_ invocation. Because of the order of the automatic variables, data types other than `Tsys` and `Tsys-Tspill` should be unaffected. The affected data types only coming into play for troubleshooting and opacity corrections, but otherwise not in more typical gain and `Tcal` analysis. However, again because of the order of the automatic variables, it is surprising that the program did not fail in more spectacular ways. Once the fix is installed, it may be prudent to re-reduce any data from logs that used more than 20 detectors per _onoff_ to check for differences in the results.

The systematic `Tsys` variation seen in issue #104 is somewhat surprising given the nature of the bug. However, with the fix installed, the variation looked as expected.

**Comment by wehimwich** [comment]
A coda: The weather data not being present appears to be because there had been no `wx` command before the first _onoff_ run. If _aquir_ is being used, it would probably be a good idea to have a `wx` in the `initp` and `prep` procedures, or their equivalents. Those could also be run manually if _aquir_ is not being used.

**Comment by BeppeMc** [comment]
I confirm, with wx in initp the gndat extracted data now contains correct meteo values.
Thanks, Beppe.
