### ISSUE TITLE
Add C function prototypes to the code

### ISSUE THREAD

**Issue by wehimwich** [nvi-inc/fs#119]
There has been some discussion of adding C function prototypes to the code where they are missing.  This would include adding headers for kernel and library calls as well as for FS code itself. This would clearly be beneficial, but there is a lot of code and testing the changes in a systematic way might be challenging.

@dehorsley had a suggestion for adding the prototypes. I think he suggest using _cproto_, but I have forgotten the details.

Another suggestion for how to do this is to incrementally add prototype to sections of code as they are worked on for other reasons. This has some advantage since it would allow testing as you go, but would less be complete initially.

I did run into a small issue while looking at incrementally adding prototypes. For functions that have `float` arguments, the prototyped functions seem to behave differently than the non-prototyped versions. Specially, the non-prototyped functions seem to convert a `float` arguments to `double` (really old C). Whereas with the prototype, the `float `arguments seem to really be `float`. In any event, calls that don't have a prototype declared don't work with the functions defined with a `float` in a prototype (and probably vice-versa). One option to deal with this might be to change the `float` arguments to `double`. Although this is what the old code was actually doing, it seems at least unpleasant to change a function that is conceptually for a `float` into one that is for `double`.

Perhaps there might also be an issue with passing structures. In the bad old days, I think passing a structure was originally always by pointer. However, at some point (maybe I misremembering), it changed so that structure were passed as local copies unless the address was taken explicitly. If so, there might be a similar issue.

**Comment by dehorsley** [comment]
See #20

**Comment by wehimwich** [comment]
Ah! I couldn't find it. I will label this as a duplicate and close it, adding the relevant parts of the above to the original.
