### ISSUE TITLE
Update to documentation - flux.ctl syntax

### ISSUE THREAD

**Issue by stuartdweston** [nvi-inc/fs#121]
Maybe add something in "fs/misc" or add to the head in "flux.ctl", so that others can add entrys applicable for their location and sensativity. 

Each line we have the following :

*               freq MHz  ---- flux 10** ----   "     FS
* source  type  min  max  log   log(f) 2log(f) size  model

Source : Name of source ( x chrs)
             For sources like 1934-638, when adding them use "m" character for "-" and a "p" for "+", ie
             1934m638 - best to use this throughout such as ctlpo.ctl and point.prc

Type : This is a "c" or a "p", I assume "c" means continuem source and "p" means point like

Min : Min frequency in MHz this line is valid for

Max : Max freq in MHz this line is valid for

From the papers referenced the flux model used is : 

      log S [Jy] = a + b * log v [MHz] + c * log^2 v [MHz]

log : is "a" in the equation above
log(f) : is "b" in above
2log(f) : is "c" in above

Size : Angular size in seconds of arc, this is important when working out is the sources resolved or bigger than the beam

FS model, there are several valid entrys : 

    gauss : need to break this down and explain significance of following values

            gauss 100 1s - I assume means gaussian profile, peak 100 something (Jy ?) with a FWHM is 1s ?
            virgoa .... gauss  80.8 40s 20s 19.2 10m 10m - So this needs more explanation

    2pts : need to break down and explain significance of following values

             cygnusa ..... 115 2pts 115s - I can't quite figure out, as I come up with an apparent size of 0.549' vs 0.457' (not sure what freq thats at). The entry for 20-2000 MHz and 2000-31000 MHz have the same "115s" ?

    disk : need to break down and explain significance of following values

            sun .... 1872 disk 0.52d - So the sun is a disk of angular size 1872" (0.52d)

Thanks

**Comment by wehimwich** [comment]
I will update the example _flux.ctl_ file with more information. Apparently no one has ever added sources before, or maybe they were able to find reasonable values.

For `c` vs `p`, it is calibrator (flux) or pointing (only). This is used in _gnplt_ to help the user select data.

The structure models are crude, but may be better than nothing. I am not sure how much we can trust them when there is significant resolution.

The `100` is the percent of the flux in that component. For single component models obviously it is all in that component. All components should sum to 100.

The `gauss` model allows you to have up to two different concentric components, each possibly having two different principal axes.

The `2pts` models assumes two equal strength point sources with the specified separation.  Perhaps the separation for the Cyngus-A model should be 110s, but that seems unlikely to make a big difference. The sizes are just quoted from tables.

The `disk` model specifies the diameter of the disk.

The `size` column was originally just informational (for the calibrators, from the paper I think), but it is used now to make a crude adjustment for extended sources when determining the size of the steps, specified in beamwidths.

**Comment by stuartdweston** [comment]
Here are the callibrators I have added locally for the Southern Hemisphere, they are monitored by ATCA and are > 10 Jy, so our 30m does see them. I doubt our 12m will see them though. In my comment I have put the date that the model coeff's were updated by ATCA. 

*
* ATCA Callibrators
* Source of data of monitored sources is obtained from the ATCA Calibrator Database
* https://www.narrabri.atnf.csiro.au/calibrators/calibrator_database.html
*
* Source   Date       Model Coeff                    Flux     Scatter Freq
* 1226+023 2021-01-30 1.930E+00,-9.798E-01,3.611E-01 23.418   0.246 @ 6600 MHz
* 2251+158 2010-12-18 7.150E-01,6.562E-01            17.897   0.191 @ 6600 MHz
* 1253-055 2021-01-30 8.203E-01,5.343E-01,-9.819E-02 15.568   0.089 @ 6600 MHz
* 1921-293 2020-09-20 3.719E-01,1.258E+00,-6.501E-01  9.252   0.025 @ 6600 MHz
* 1934-638 2021-02-21 1.528E+00,-1.044E+00,-1.104E-01 3.965   0.006 @ 6600 MHz
* 2134+004 2020-09-20 6.702E-01,1.131E+00,-8.400E-01 10.787   0.032 @ 6600 MHz
* 0723-008 2021-02-08 1.198E+00,-4.557E-02,-3.223E-01 8.794   0.135 @ 6600 MHz
* 1830-210 2021-01-08 1.005E+00,5.835E-01,-3.969E-01 16.467   0.069 @ 6600 MHz
*
*               freq MHz  ---- flux 10** ----   "     FS
* source  type  min  max  log   log(f)  2log(f) size  model
   1226p023 p  6400  6800 1.93  -0.9798  0.3611    1  gauss 100 1s
   1934m638 p  6400  6800 1.528 -1.044  -0.1104    1  gauss 100 1s
   2251p158 p  6400  6800 0.715 0.6562   0.0       1  gauss 100 1s
   1253m055 p  6400  6800 8.203 0.5343  -0.09819   1  gauss 100 1s
   2134p004 p  6400  6800 0.6702 1.131  -0.84      1  gauss 100 1s
   0723m008 p  6400  6800 1.198 -0.04557 -0.3223   1  gauss 100 1s
   1830m210 p  6400  6800 1.005 0.5835 -0.3969     1  gauss 100 1s

So as per your comments above I need to change "type" and "model". They are point like sources for the 30m so good for pointing as well. So for "c" or "p" can we have a "b" (both) ? 

The above models also work for X-Band, so perhaps the min/max freq can be adjusted. I am currently using them for C-Band to point on and callibrate.
