### ISSUE TITLE
Debug Levels

### ISSUE THREAD

**Issue by stuartdweston** [nvi-inc/fs#122]
I wonder if it is possible to implement a debug level to get more or less verbose feedback while the FS is running

At the moment this is comming from working out calc's for 👍 

> What I can't work out is why it comes up with a Tsys of 100.000 :
>
> 021.131.23:05:42.88#fivpt#tsys  71.274  32.456 100.000  0.1592

That does look suspicious though the error estimate seems reasonable.
Obviously if it always comes up as exactly 100 then something is wrong.
**Unfortunately you don't get to see how it works that out** - you should run
caltsys repeatedly and check that the noise diode is working correctly.

> In the past I have managed to get a value in there, can't remember what I did
> as it was some years ago. But now with my current rxg file setup it always
> put's in 100.

So something is wrong - it should be giving you a value that squares with the
value reported by onoff for that detector, which it doesn't.

But could also be applicable elsewhere

**Comment by varenius** [comment]
I believe you can set "echo=on" and you will get more detailed output in the log.

**Comment by varenius** [comment]
As for your mystery about Tcal -100, I wonder: which RXG file are you using? Could you post it here? As per the FS help (https://github.com/nvi-inc/fs/blob/master/help/onoff.___#L113) it would seem to me that you have put Tcal -100 in your RXG file.

**Comment by stuartdweston** [comment]
I was thinking more like commercial software having say debug 0-5 say (0 nothing - 5 v.v.verbose)

I did use in the past log4net wich was very very usefull for filtering debug msg's and finding what you wanted. 

Just an idea ;-)

**Comment by wehimwich** [comment]
@stuartdweston, I think also answered your question about Tsys being 100 in separate emails. They basically said what @varenius wrote above. Please let us know if that doesn't solve the issue.

Regarding multiple levels of debug output: The `echo` output is not intended to be a user feature. It is intended for debugging. We could add multiple (or maybe disjoint) levels of debug output, but I am not sure we have the resources for that to be at the top of the list anytime soon.

In the meantime, you might want to consider:

1. I do find it useful sometimes to filter the log  using `tail -f` or (with the server: `fsclient -n -w -s`) piped into _grep_ to select the output I am (or suppress the output I am not) interested in. That can be useful for both `regular` and `echo` output. It allows a lot of flexibility. 
2. For antenna interfaces that generate a lot of `echo` output, I have sometimes implemented a separate (disjoint) _local_ `aecho` command for that.

**Comment by stuartdweston** [comment]
Here is the problem rxg file : (bugger github doesn't like the rxg extension) 

* c.rxg - c band receiver parameter definition
*
* first line: LO values and ranges, format:
*  type   frequencies
* if type is range, the two values: lower and upper frequencies
* if type is fixed, then the fixed value
* frequencies in MHz
*
fixed 5843 
*
* 2nd line: creation date
* format:  yyyy ddd or yyyy mm dd (0 is valid for all for intial set-up)
*
2018 07 05 
*
* 3rd line: FWHM beamwidth
* format: model value
*
* if model is frequency, then fwhm=value*1.22*c/(freq*diameter)
*                        value is 1.0 if omitted
* if model is constant, then fwhm=value (degrees)
*
frequency 1.0
*
* 4th line polarizations available
*
* one of both of lcp and rcp
*
lcp rcp 
*
* 5th line: DPFU (degrees/Jansky) for polarizations in previous line in order
*   J. McCallum 13032020
*   I'm a bit confused with the values in the DPFU and gain lines - do you 
*   really have 40 Jy/K or does the polynomial gain curve bring that down? 
*   I'd expect a PDFU of ~0.1 for a 30m dish.
*
*0.025 0.025
0.1 0.1
*
* 6th line: gain curve (only one) for ALL polarizations in 4th line
* TYPE FORM COEFFICENTS ... [opacity_corrected]
*
* FORM = POLY only for now
* TYPE - ELEV and ALTAZ only for now
* COEFFICENTS - variable number of number values
* opacity_corrected - optional final field, if present it indicates that
*                     the curve is opacity corrected
*
* maximum coefficents 10
*
* 1st Gain curve for 6.7GHZ
*
*             3           2       
* -0.0001529 x + 0.02853 x - 1.744 x + 122.3
* Taken from data produced by T.Natusch Dec 2014
* Used Python Numpy Polyfit, S.Weston 10/7/2018
*
ELEV  POLY 1.0 0.0 0.0 0.0 0.0 0.0
*ELEV POLY 122.3 -1.744 2.853e-02 -1.529e-4
*
* 7th and following lines: tcal versus frequency
*     Format: POL FREQ TCAL
*     where:
*            POL    polarization rcp or lcp
*            FREQ   frequency (MHz)
*            TCAL   degrees K
*
*     ends with a line containing end_tcal_table
*
*     MAXIMUM ENTRIES 400, group by polarization
*                          then sorted by increasing freq
*
* Measured SEFD in C-Band ~ 650Jy (http://adsabs.harvard.edu/abs/2015PASP..127..516P)
* So TCAL ~ 90 K
*
rcp 6516.00 9.872
rcp 6526.00 9.872
rcp 6536.00 9.872
rcp 6546.00 9.872
rcp 6656.00 9.872
rcp 6666.00 9.872
rcp 6676.00 9.872
rcp 6686.00 9.872
lcp 6516.00 9.872
lcp 6526.00 9.872
lcp 6536.00 9.872
lcp 6546.00 9.872
lcp 6656.00 9.872
lcp 6666.00 9.872
lcp 6676.00 9.872
lcp 6686.00 9.872
end_tcal_table
*
* Trec: receiver temperature
*
0.0 0.0
*295.15 295.15
*257.78 257.78
*249.0 249.0
*
* Spill over table
*
* 9th and following lines: Spillover versus frequency
*     Format: Elevation Tspill
*     where:
*            POL    polarization rcp or lcp
*            FREQ   frequency (MHz)
*            TCAL   degrees K
*
*     ends with a line containing end_spillover_table
*
*     MAXIMUM ENTRIES 20
end_spillover_table

**Comment by stuartdweston** [comment]
Looking at the code in incom/get_rxgain_files.c I see a commented out line to print the file names, so I uncommented and did a make

When  starting the FS I now see it reads the correct rxg files :

running incom
 file /usr2/control/rxg_files/cl.rxg
 file /usr2/control/rxg_files/c.rxg
 file /usr2/control/rxg_files/l.rxg
 file /usr2/control/rxg_files/x.rxg

But doesn't explain the Tsys 100 in fivpt, as in the "c.rxg" I have not used -100 (see earlier email and response to issue).

**Comment by wehimwich** [comment]
The issue that started this was moved to #125. Bugs aside, we try to have the needed information to understand what is happening in the logs. The _fivpt_ and _onoff_ log entries show the Tcal values used. As of _10.0.0_, the `lo` command also shows which _.rxg_ file is in use. The use of `echo=on` is a powerful tool for verifying  the communication with devices, and its output can be filtered for what is relevant. A local, disjoint, `aecho` command can be useful for antenna communication debugging. One reason we distribute source code is so that people can locally investigate errors they encounter and quickly overcome obstacles to collecting data (please send us your fixes so other users will benefit). It could be useful of course to have graded levels of debug, but I am concerned about the implementation and maintenance burden it could create. That should be opened as a new (uncluttered) issue if it seems warranted. For now, I am more concerned about cleaning up our existing errors messages since some are particular uninformative for historical reasons, e.g., #83 and #124.
