### ISSUE TITLE
Trec and spillover in rxg files?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#123]
I have had multiple questions about the meaning of "Trec" in an RXG files. I have only seen this with value 0.0, but apparently some people have values here. My understanding is that it is not used for generating Tsys/Tpi/SEFD values. It would, however be good if someone who knows more about Trec could explain clearly how and when this parameter is relevant.

Same goes for the "spillover table" which I have also only seen as 0.

**Comment by wehimwich** [comment]
I haven't looked at this for quiet awhile. These are used in _gnplt_ when correcting for opacity, usually at higher frequencies I believe.

**Comment by varenius** [comment]
Thanks, that was my educated guess too - the terms are needed when there is a need to disentangle the various contributions to Tsys (= Trec + Tcmb + Tsky + Tground ...). I think we can close this for now.
