### ISSUE TITLE
Question: For BBCs not identical to RXG file, what interpolation is used?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#129]
As in the title, I suspect linear or nearest interpolation is used to infer Tcal values for frequencies which may not be in the RXG file? Just curious.

**Comment by wehimwich** [comment]
Linear. However, if you are off the end of the table, it extends the nearest value. This has implications for multi-band receivers. It might be better to have one _.rxg_ file per band. That way you won't involve a different band in the interpolation. That may not be a problem in general, but for some cases it might. OTOH, is just extending the nearest value better? It is probably best if the frequency falls in the available table for the band. There are other reasons for having different _.rxg_ files per band, having different gains curves per band might be the most significant.
