### ISSUE TITLE
fivpt slightly underestimates Tsys for continuous cal

### ISSUE THREAD

**Issue by wehimwich** [nvi-inc/fs#131]
https://github.com/nvi-inc/fs/blob/0adbc516518f3a59e95c6539ab6212338db3400d/fivpt/tsys.f#L237-L240

The code only uses the the CalOff value in the numerator of the Tsys calculation for continuous cal. This lowers the reported Tsys level by about one-half the Tcal value. As a result, Tant for the source is slightly higher. The fitting process for the peak removes a background level, so the pointing fit results are unaffected. Perhaps this has some benefit since it makes it less likely that Tant will be negative, which is always a little unpleasant. It does affect the Tsys derived values of the `#fivpt#perform` record, but those are mostly a curiosity and typically not used for any significant work. Anyway, it should be fixed.

It looks like it is a bug introduced in the merge of _9.13.2_ and _9.12.13_ (while fixing #125). Inserting

````
            tpia=(tpia+tpical)/2
````

before line 239 above should fix this issue. It needs to be tested.

**Comment by varenius** [comment]
Seems like this basically only needs testing? Would you like to test it using the OSO DBBC3? If so, we can arrange this.

**Comment by wehimwich** [comment]
Okay. What would be the scenario for doing this? I am a bit hesitant about moving big pieces of metal when I am not able to view them in realtime from nearby.

**Comment by varenius** [comment]
We can arrange 
a) video feed real-time,
b) me looking at the telescope real-time when I am in Onsala.
I can be responsible to keep track of metal not hitting anyone or anything. 
If this seems interesting, perhaps testing this some time tue,wed,thu next week?
