### ISSUE TITLE
vdif related errors on DBBC3 branch

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#141]
As per discussion in #138 we should use 8000 bytes as VDIF payload size for DBBC3. Onsala previously used 8192 bytes. In #138 I reported that after changing DBBC3 to use 8000 bytes, the FS seemed happy. 

I then proceeded to see if I could re-compile the FS to use 8192 bytes as VDIF payload (changing https://github.com/nvi-inc/fs/blob/ed/dbbc3/clib/dbbc3_core3h_modex_util.c#L355), just because I was curious. I set the DBBC3 to use 8192, but I got vdif-errors on FS. Not sure why.

Then I decided to switch back to 8000 again, which worked before. I set DBBC3 to use 8000 bytes as VDIF payload size, and recompiled the FS again with 8000 bytes. Surprisingly, it does not work now. I wonder if I broke something this time, OR if I managed to swap some setting in the DBBC3 without intending to do so.

The FS10 DBBC3 tsys logging works anyway, despite the FS errors, but I'd like to understand them.

The errors appear when I use the core3h_modeX command, and I get errors like:

```
2021.252.11:38:13.18?ERROR dr -616 Core3h board    1 vdif_frame width is not correct.
2021.252.11:38:13.18?ERROR dr -617 Core3h board    1 vdif_frame channels is not correct.
2021.252.11:38:13.18?ERROR dr -618 Core3h board    1 vdif_frame payload is not correct.
2021.252.11:38:13.18?ERROR dr -601 DBBC3 Core3h board 1 configuration is not correct.
```

I attach a logfile with the usual experiment setup (vo1245) where I have included the core3h_modeX commands. I ran this with "echo=on" so all the details from the DBBC3 should also be there. Can anyone spot the mismatch?
[tt8.log](https://github.com/nvi-inc/fs/files/7136216/tt8.log)

I think perhaps it could be useful if @wehimwich could login remotely and investigate? If this is interesting, let me know via email and we can arrange access.

**Comment by wehimwich** [comment]
This was definitely a bug. The `vdif_frame` parameters were only calculated if `force` was used. Although the initial model was that the operator would use the setup procedure with `force` before using it without (which is just for checking the setup), that isn't a necessary assumption. In particular it won't work if we end up using only the boot configuration to avoid timing issues with a re-sync (which is required with `force`). I will push a commit that fixes this shortly.

Thanks @varenius for finding and reporting this issue. Thanks also for arranging remote testing. That sped up the resolution process a lot.
