### ISSUE TITLE
DBBC3 DDC_U v125 BBC width 128 MHz not reflected in ONOFF?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#148]
I'm doing some tests with DDC_U v125. Many things work, but I am surprised by one thing today. I'm testing 128 MHz wide BBCs. In the example log, this is set by e.g. using
```
2021.285.14:04:48.21&dbbcbb128/bbc001=2560,a,128
```
The LO is set by
```
2021.285.14:04:49.82&ifdbb/lo=loa,7700,lsb,lcp
```
When ONOFF starts, it gives this calculation of the center frequency for 001l detector:
```
2021.285.14:07:18.15#onoff#    De      Center  TCal    Flux    DPFU     Gain    Product   LO    T   FWHM
2021.285.14:07:18.15#onoff#APR 001l   5156.00 1.706  612.23  0.025000 1.00000  0.025000  7700.00 p 0.30790
```
I disagree with this. 7700-2560 = 5140, so center would be 5140+0.5*(bbc bandwidth) = 5140+64=5204 MHz. Instead, the calculated center of 5156 MHz seems to assume 32 MHz BBC bandwidth. Is this a bug, OR is it somehow not acknowledged properly because of the core3h_modeX errors in the log (which is because I was lazy and kept bitmasks online also for mask2 and mask4, although I'm not using those BBCs here)?

Please see attached logfile [t128.log](https://github.com/nvi-inc/fs/files/7333619/t128.log) for more details.

**Comment by wehimwich** [comment]
Yes, it looks like the 32 MHz BW is hard coded for DBBC3. That is left over from 9.12. It is a simple fix. I can probably make a new version in a day or two if you (or I) can test it. Thank you for finding this (I'm sorry you had to).
