### ISSUE TITLE
DBBC3 Tsys monitor window missing one character in lower right

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#151]
In case of LSB BBCs with large or overflowing Tsys, it seems there is a character missing in the DBBC3 Tsys monitor window to the lower right. Example screenshots:
<img width="251" alt="Screenshot 2021-10-13 at 09 30 37" src="https://user-images.githubusercontent.com/8872291/137087410-547a497f-7862-41fa-84e1-3c638e40a162.png">
<img width="261" alt="Screenshot 2021-10-13 at 09 30 41" src="https://user-images.githubusercontent.com/8872291/137087415-b47761ef-ba92-4b8a-93b4-670207a1f724.png">

**Comment by varenius** [comment]
I have tested the latest working copy on "freja". The lower-right character issue appears fixed now, but instead the "e" in "Rec" seems gone in the top right? Example
<img width="250" alt="Screenshot 2021-11-29 at 11 25 10" src="https://user-images.githubusercontent.com/8872291/143851225-2cbc24e2-7b7b-4587-8be8-c138217e9e03.png">
:

**Comment by wehimwich** [comment]
I can't count. Even worse, I was off by two. But it looks like I was on the right track. I have updated your local copy. Please restart it and see how it looks now.

**Comment by varenius** [comment]
Seems happy now:
<img width="249" alt="Screenshot 2021-11-30 at 19 11 48" src="https://user-images.githubusercontent.com/8872291/144103973-44add786-bc53-4039-8b30-70c9df92c20d.png">

I consider this fixed. But perhaps you want to commit this change before closing the ticket if you have not already?
