### ISSUE TITLE
Drudg the e-VLBI vex files with the keyword target_correlator

### ISSUE THREAD

**Issue by wehimwich** [nvi-inc/fs#165]
### Discussed in https://github.com/nvi-inc/fs/discussions/162

<div type='discussions-op-text'>

<sup>Originally posted by **vlbi-jun-yang** November 10, 2021</sup>
Currently, stations have to manually change the recorder to none to _drudg_ e-VLBI vex files. If _recorder=none_ is defined in the vex files, station might let _drudg_ to overwrite the local setup and then _drudg_ e-VLBi file automatically. To investigate its feasibility, I have communicated with JIVE. This requires JIVE to provide another input station data file for users to run the NRAO _Sched_ or the JIVE _py-Sched_.  This may cause additional issues. So, in practice, it is not promising than I thought. 

To avoid the manual change of the recorder, I have wrote a local script to comment out the commands dedicated to the disk-recording observations.  Still, I need an option for my script to define the e-VLBI mode. Later, I propose JIVE to use the keyword _target_correlator_ to define the e-VLBI mode clearly in the vex files.  We have agreed on seting _target_correlator = JIVE_E-VLBI_. The keyword is not really used by _drudg_. So,  _drudg_  is happy for the new value.  

At another level, I am wondering whether we can get _drudg_ to use the keyword as an alternative way of _recorder=none_ for the e-VLBI observations.  </div>

In the _10.1_ release, _drudg_ will have a _skedf.ctl_ option to change the recorder to `none` if `target_correlator` contains `e-vlbi` (case insensitive).

**Comment by vlbi-jun-yang** [comment]
Thanks for providng the new option for stations to support the e-VLBI observations.

**Comment by vlbi-jun-yang** [comment]
Thanks for providing the new option for stations.

**Comment by wehimwich** [comment]
Was closed by 75d7c2fe459484bb13e2d54fe590ea3a25a06505
