### ISSUE TITLE
Minor typos in /usr2/fs/st.default/control/dbbc3.ctl

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#173]
Testing 10.1.0-beta1. In file /usr2/fs/st.default/control/dbbc3.ctl I note that:
- All values have 2 spaces indent, except the last row. It is " 128" but I think it should be "  128" to match the others?
- DBBC3 firmware default versions do not make sense. The lowest DDC_U firmware version is 125, and the lowest DDC_V version that supports multicast is 124. Despite this, it says:
```
* DDC_U firmware version (v121 or later)
  v121
* DDC_V firmware version (v121 or later)
  v121
```
I suggest changing these to v125 and v124 respectively.

**Comment by wehimwich** [comment]
Thanks for reporting these. I will change the spacing and update the example version numbers. I am inclined to not change the minimum shown in the comments. The support dates back to the _v121_ version even if the DBBC3 features and the FS support were more limited. I don't know if there were even different `DDC_U`/`DDC_V` version at that time. It is of course necessary to put the correct version in the file for FS to work properly, but the file parsing still accepts versions back to _v121_.
