### ISSUE TITLE
some ERRORs not included in ERCHK window?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#174]
After installing FS10.1-beta1 DRUDG will include a call to "fb_config" for ONSALA60 since we have a flexbuff for recording. It seems I forgot to define this procedure, since we normally do not need any special setups for S/X obs (but we do use this procdure for VGOS obs with Oe/Ow). The calls to "fb_config" during rd2203 thus generated the error
2022.083.10:32:46.95?ERROR sp   -4 Unrecognized name (not a function or procedure).
since the procedure was not defined. So far so good. However, the errors were missed because they are apparently not shown in the erchk "Errors" display on the FS,. This does show other errors, but this "sp -4" seems to not be included. Is this on purpose? Would it not make sense to include all errors in the "Errors" display?

**Comment by jvrgnzlz** [comment]
As a user, I would prefer to have this error included in the _erchk_ window. It would make easier for the oper to detect errors like the one starting the thread. Typos can be introduced when defining local procedures, and although they should be tested before used in real observation, it is not easy to spot the error message in the log file for some of the present schedules, like VGOS. I don't see a drawback in having them in the error window, from the user perspective.

**Comment by wehimwich** [comment]
I suggest we change _erchk_ to use a control file to specify how errors are displayed (or not displayed). This can be customized locally to the station's preferences.  An initial version of the control file can provide the current behavior except that `sp` errors will be displayed.

**Comment by varenius** [comment]
sounds good to me!
