### ISSUE TITLE
drudg enddef

### ISSUE THREAD

**Issue by BeppeMc** [nvi-inc/fs#177]
Hi all,
I try to drudg the geo r41046, and last procedure threadsx was ended with 'endef' instead 'enddef' causing fs claim of 'Unrecognized name' every call of threadsx.
Strangely the other procs in file are properly ended with enddef.

**Comment by wehimwich** [comment]
Thanks @BeppeMc. The generation of `thread` procedures uses new unique code. A fix is coming shortly.
