### ISSUE TITLE
Request : ONOFF produce G/T_sys Value

### ISSUE THREAD

**Issue by stuartdweston** [nvi-inc/fs#197]
Request : ONOFF produce G/T_sys Value

We have a column with SEFD, please can a column be added to give the G/T_sys figure as well. It looks to me like the FS has all the data to do this.

It seems outside Radio Astronomy everyone else uses G/T_sys, especialy in the commercial world.

Thanks

**Comment by wehimwich** [comment]
We have to be slow to add columns. G/T is redundant with the frequency and SEFD, so I would rather not add it (there is a pending request for SEFD<sub>ratio</sub>, which is unique, but that is a bigger job, related to #163). We are more radio astronomers than communications engineers, so I would rather stick with SEFD. :)

How about we have a script you can run on a log to print the SIG and VAL lines with G/T appended? That way you can get it when you need it, but otherwise we can be radio astronomers.

**Comment by stuartdweston** [comment]
Well Warkworth now wear's two hats one is VLBI the other is LEO/DSN comm's. In the commercial sector and LEO/DSN they work with G/T_sys. As do a few other IVS antennas (Au, SA) these days ;-) fact of life and $'s.

A script would work fine. To parse the ONOFF and add a column. Need to factor in other things though like Station Coords, Source Elevation, Met, refractive index ... etc which is all inside the FS shared memory. Hence my request.

**Comment by wehimwich** [comment]
I am guessing that you don't need it very often.

What I would do is pretty simple, log<sub>10</sub>(8πk/λ<sup>2</sup>SEFD), everything is SI units. I think it is at elevation, but it might be worth having an option to use the gain curve value, which can come from the _onoff_ `APR` lines. If some one wants to provide how to handle absorption, we might be able to get that in.

I think there is some danger in thinking this is highly accurate. I don't tend to trust SEFDs to better than about 10% (0.4 dB) on a good day. So refining the calculation a lot may not be worth it.

**Comment by wehimwich** [comment]
Sorry, that should have been 10log<sub>10</sub>().

**Comment by stuartdweston** [comment]
>>I am guessing that you don't need it very often.
Correct

I have a paper on the G/Tsys calcs that they claim is within 5% as used by our new owners here. Morgan et al "Determination of Earth Station Antenna G/T Using the Sun or the Moon as an RF Source", SSC18-X-05.

**Comment by stuartdweston** [comment]
Yo I'd worked out the 10 Log_10() bit ;-) I used it on my gain curve data to give our new owner/operator a rough G/Tsys as he's in discussions with JPL

**Comment by wehimwich** [comment]
> > I am guessing that you don't need it very often.
>  Correct

Maybe a hand calculation would be enough then,  but I can understand that it is nice to have something reduced to code.

> I have a paper on the G/Tsys calcs that they claim is within 5% as used by our new owners here. Morgan et al "Determination of Earth Station Antenna G/T Using the Sun or the Moon as an RF Source", SSC18-X-05.

Could be. It is beyond what I know/expect. You are going to be limited to what _onoff_ can do anyway.

I am not sure how soon I can get to it. Hopefully, a hand calculation will suffice for now.

**Comment by wehimwich** [comment]
I made a draft script to generate G/T from _onoff_ log output. You can find it at: [govert](https://raw.githubusercontent.com/nvi-inc/fs/ed/govert/misc/govert). Please give it a try and let me know if it seems useful. It just uses the simple calculation above, but we can improve it.

To try it, you can download it, maybe to _/usr2/log_. Then make it executable:

```
cd /usr2/log
chmod a+x govert
```

Then to run it on a log, maybe _point.log_, you can use:

`./govert point.log`

The output will come to `stdout`. Of course you can pipe it through _less_ or redirect it to a file. You can get the help output with:

`./govert -h`

I included a `-u` option to map the SEFD to unity gain. It adjusts the printed SEFD values and removes the elevation and other reported quantities that are no longer relevant from the output.

**Comment by stuartdweston** [comment]
Thanks I'll try it today as I have some onoff's from the weekend.


Dr. Stuart Weston

Mobile: 021 713062

Skype: stuart.d.weston
Email:  ***@***.***

http://www.atnf.csiro.au/people/Stuart.Weston/index.html


School of Engineering, Computer and Mathematical Sciences
Faculty of Design and Creative Technologies
Auckland University of Technology, New Zealand.


________________________________

**Comment by stuartdweston** [comment]
Thanks Ed it works very nicely :-) 

2023.126.10:32:36.91#onoff#    source       Az   El  De I P   Center   Comp   Tsys  SEFD  Tcal(j) Tcal(r)   G/T
2023.126.10:32:36.91#onoff#VAL moon        72.6 55.0 1u   1 l   8108.00 0.0000 -100.  984.8   0.000  0.00   44.112
2023.126.10:32:36.91#onoff#VAL moon        72.6 55.0 2u   1 l   8208.00 0.0000 -100. 1011.3   0.000  0.00   44.103
2023.126.10:32:36.91#onoff#VAL moon        72.6 55.0 3u   1 l   8308.00 0.0000 -100.  966.0   0.000  0.00   44.407
2023.126.10:32:36.91#onoff#VAL moon        72.6 55.0 4u   1 l   8408.00 0.0000 -100.  939.7   0.000  0.00   44.631
2023.126.10:32:36.91#onoff#VAL moon        72.6 55.0 5u   1 l   8508.00 0.0000 -100.  926.8   0.000  0.00   44.794
2023.126.10:32:36.91#onoff#VAL moon        72.6 55.0 6u   1 l   8708.00 0.0000 -100.  875.5   0.000  0.00   45.243
2023.126.10:32:36.91#onoff#VAL moon        72.6 55.0 7u   1 l   8808.00 0.0000 -100.  893.8   0.000  0.00   45.252
2023.126.10:32:36.91#onoff#VAL moon        72.6 55.0 8u   1 l   8908.00 0.0000 -100.  865.4   0.000  0.00   45.490

That is for the 30m in X-Band. We will check the values against another method for confidence ;-)

**Comment by wehimwich** [comment]
Great. Let me know if it agrees. I checked it by hand once, but that doesn't mean I did everything correctly. More confirmtion is always better.

Those are similar values to what Gilreek (26m) got at X-band.
