### ISSUE TITLE
Output typo in fesh warning when schedule file already exists

### ISSUE THREAD

**Issue by kpgosite** [nvi-inc/fs#34]
Issue: When using fesh to download a schedule, and that schedule already exists on the computer, the error/warning fesh returns contains a typo.

The current return is (____ is path and the schedule file);
"____ exits, delete or use '-f' to get fresh schedule"
where it should state
"____ exists, delete or use '-f' to get fresh schedule"

FWVersion: 10.0.0-alpha2-57-G10396864 and 10.0.0-alpha2-58-g229f696e (20m and 12m respectively)
OSVersion: FSL10
Station: KPGO 20m and 12m

**Comment by dehorsley** [comment]
Thanks for the report! Glad to see you on GitHub :)
