### ISSUE TITLE
Compatible DBBC3 firmware versions?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#35]
FS10 seems to ship equip.ctl with the default lines
```
* DBBC3 firmware version, bbcs/if, ifs
  v223 16 8
```
According to the Hat-Lab hompage, https://www.hat-lab.cloud/downloads-dbbc3-ddc/, the available firmwares are: 121, 123 (mostly used by e.g. Onsala so far in VGOS obs), 124 (should be 123 with multicast; see #32 ), 125 (experimental)

Therefore I was puzzled by the "223" in the default equip.ctl. Should it perhaps be 123? Also, which firmware versions are currently supported by the FS; is this listed somewhere?

**Comment by wehimwich** [comment]
That was an oversight I guess. The code accepts anything beginning with v121 in **equip.ctl**. However, no functionality is controlled by the version number, yet.

I see the logs for Ow/Oe show v221 for the version in **equip.ctl**. Perhaps my fault as well.
