### ISSUE TITLE
fesh: respect directories as specified in skedf.ctl

### ISSUE THREAD

**Issue by jfhquick** [nvi-inc/fs#65]
Since fesh is adjunct to drudg, it should use the same directory parameters as drudg does as specified in control/skedf.ctl.

**Comment by dehorsley** [comment]
This might be something to go in fesh2. I dread writing the parser for skedf.ctl in bash.

**Comment by wehimwich** [comment]
Yeah. Right. However it might be possible by embedding a command line perl script for each directory parameter. I will try to give it a look. Still needs other data centers of course.
