### ISSUE TITLE
Does ONOFF/acquir respect horizon mask?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#99]
During a VTC telecon yesterday, the question was posted: does ONOFF/acquir respect a horizon mask? If not, using it is problematic in some cases. I know it is possible to restrict angles in acquir ctl file, but can one define a "full" horizon mask there/elsewhere?

**Comment by ubach-ef** [comment]
Yes, it does. You can define a mask in the ctl-file that acquir uses, e.g. a rough mask is implemented at Effelsberg for the hill in the east and west and avoids below 20 deg completely.
```
* Elevation mask for lower elvation limit: AZ EL AZ EL ... AZ
* may contain multiple lines, an incomplete line ends with an EL
*
   0 20 30 30 80 30 130 20 260 20 270 25 330 25 340 20 360
```
 The lower limit of 20deg of course does not allow to fit for a gain curve, but we use out local control system to do that.

**Comment by varenius** [comment]
Gotcha, thanks!
